### PR TITLE
Respawn

### PR DESCRIPTION
**Pull request by arlolra**
I rebased #31 on master and added a test and the ability to run `npm test`, should you so desire.

### CODE REVIEW

**Comment by trodrigues** [comment]
Any ideas on when this will be properly merged? We've been using this fork in production across 3 different apps for about a month now with no issues so far.

**Comment by vgrichina** [comment]
0.2.2 version in npm repo doesn't have `--keepalive`, is it intentional?

**Comment by vgrichina** [comment]
BTW, I am also confused how Github has 0.2.1 version and `--keepalive` and npm has 0.2.2 without it, which I cannot find on Github.

**Comment by vgrichina** [comment]
@guille maybe you can comment on these?

**Comment by rauchg** [comment]
Most likely we mis-published under `0.2.2`

**Comment by greelgorke** [comment]
@guille which version in npm does have this pr?

**Comment by vgrichina** [comment]
@greelgorke version 0.2.2

**Comment by greelgorke** [comment]
@vgrichina nope, it doesn't. i 've installed 0.2.2 and there is no newer publish of it on npm.

**Comment by vgrichina** [comment]
@greelgorke did `npm install -g up` right now. 

Have following result, so I am not sure what are you talking about.

```
up --keepalive

  error: unknown option `--keepalive'
```

**Pull request merged**
