### PR TITLE
Added support for the --require option to enable CoffeeScript (or other transcoders) when loading the server

### PR DESCRIPTION
**Pull request by simonexmachina**
Simply added code to `require` each of the `--require` options before calling `server = require(file)`

### CODE REVIEW

**Comment by rauchg** [comment]
Needs README docs.

**Comment by simonexmachina** [comment]
Good point, that's done now.

**Comment by rauchg** [comment]
Excellent. One final nitpick, it'd be nice to support `--require|-r`

**Comment by simonexmachina** [comment]
Maybe I'm not understanding what you're asking for. I've updated the README
file to explicitly indicate that -r can be used for transpiler support:

```
- Tranpilers such as CoffeeScript can be supported with `--require|-r
```

coffee-script`

Is that what you mean?

**Pull request merged**
